### ISSUE TITLE
Teach Ava how to do {.codesmall} code

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/Intro_to_R_class#54]
https://github.com/jhudsl/intro_to_R_class/blob/eb54edd589afeda00356b13cb7d30e6026d73a0c/Data_Cleaning/index.Rmd#L188

I added this and it doesn't work when I try to knit it. What am I missing? 😛

**Comment by carriewright11** [comment]
Nope! That's my fault - I didn't update style.css somehow! I will fix that

**Comment by avahoffman** [comment]
Works perfectly. thanks!
