### ISSUE TITLE
Use `exrcise` package to automatically set up your exercises and keys

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/Intro_to_R_class#71]
https://github.com/AlexsLemonade/exrcise

Exrcise deletes the solutions from the Rmd in your exercises so you can write once and then print out the blank version and the solution version. 

When we set up github actions to automatically set things up for this course, we should also set up this package to automatically set up the exercise Rmds.

**Comment by avahoffman** [comment]
love this!
