### ISSUE TITLE
Naming positional arguments - best practices in R?

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/Intro_to_R_class#77]
For python, it's best practice to name positional arguments.

I'm not sure how the R community feels about this. My preference is that we follow a similar standard. Eg:

Do this:
```
dplyr::arrange(mtcars, by = hp)
```

Instead of:
```
dplyr::arrange(mtcars, hp)
```

Not sure if there's a styler that will do this. If not, we can check this in PR reviews. Willing to be overruled if the R community feels otherwise 😛 

### todo:

- [ ] Someone will have to go thru the lectures and labs + check for this
- [ ] Someone should add (briefly) to Basic R what an argument is, and why it sometimes works without specifying the argument name (i.e., mention positionality)

**Comment by carriewright11** [comment]
thought it might make sense for us to check each of our lectures
