### ISSUE TITLE
Functions lab -bonus

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/Intro_to_R_class#87]
one of the students was confused by the wording "filter out" (and myself in the moment :P) maybe we could add more details about what we mean

**Comment by avahoffman** [comment]
yes!

**Comment by avahoffman** [comment]
https://github.com/jhudsl/intro_to_R_class/blob/c32064479a279f7feabd43c7db6f79b1059c391e/Functions/lab/Functions_Lab_Key.Rmd#L92
